# Check interval
CHECK_INTERVAL: 15  # Seconds to wait between each check of the aircraft_dump_url

# MQTT 
MQTT_BROKER: '10.10.10.21'
MQTT_BROKER_PORT: 8883
MQTT_USER: '136worple'
MQTT_PWD: '011020MQTT'
MQTT_CLIENT_ID: 'flights_client'

# HTTP
FASTAPI_PORT: 47474

# Feed topics
MQTT_TOPIC_VISIBLE: "flights/visible"
MQTT_TOPIC_CLOSEST_AIRCRAFT: "flights/closest_aircraft"

# User location
use_lat_lon_from_config: False # If False, replace by values from receiver dump file
USER_LAT: 51.462649
USER_LON: -0.328869

# Tracking
##nearest_aircraft: True
##nearest_aircraft_in_interest_zone: True

# Watch heading
##watch_heading: 270 # Only consider aircraft with this heading; Useful, for example, to watch a take off or landing path
##heading_range: 360 # Degrees plus or minus the watched_heading which still fall into the conisderation range 

# Watch zone
LAT_SOUTH: 51.45538
LAT_NORTH:  51.48787
LON_WEST: -0.37257
LON_EAST: -0.28753
max_alt: 3000
min_alt: 0

# Altitude & Distance
RADIUS: 10 # distance in unit below from user position 
DISTANCE_UNIT: mi # mi for miles or km for kilometers
ALTITUDE_UNIT: ft

# Source
DUMP_URL: 'http://10.10.30.139:30053/ajax/aircraft'
CONFIG_FILE_PATH: "../config/config.yaml"
EXAMPLE_DUMP_FILE_PATH: "../config/planefinder_dump_structure.json"
VISIBLE_JSON_FILE_PATH: "../output/visible.json"
CLOSEST_AIRCRAFT_JSON_FILE_PATH: "../output/closest_aircraft.json"
ALL_AIRCRAFT_JSON_FILE_PATH: "../output/all_aircraft.json"
FLIGHTS_WITHIN_DEFINED_ZONE_JSON_FILE_PATH: "../output/flights_within_defined_zone.json"
FLIGHTS_WITHIN_DEFINED_RADIUS_JSON_FILE_PATH: "../output/flights_within_defined_radius.json"

# Key names for referenced keys in the dump file
tracked_parent: 'aircraft' # Name of the parent key of tracked flights in the dump, e.g., 'aircraft'
icao_id: 'False' # Example val: 'AA37CE'
callsign: 'callsign' # Example val: 'AAL38'
flightno: 'flightno' # Example val: 'AA38'
route: 'route' # Example val: 'MIA-LHR'
type: 'type' # Example val: 'B772'
latitude: 'lat' # Example val: '51.47807'
longitude: 'lon' # Example val: '-0.185242'
altitude: 'altitude' # Example val: '3425'
heading: 'heading' # Example val: '271'
speed: 'speed' # Example val: '177'
reg: 'reg' # Example val: 'N758AN'
