# Logging configuration
LOG_LEVEL: "ERROR"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Check interval
CHECK_INTERVAL: 15  # Seconds to wait between each check of the aircraft_dump_url

# MQTT configuration
MQTT_BROKER: '10.10.10.21'
MQTT_BROKER_PORT: 8883
MQTT_USER: '136worple'
MQTT_PWD: '011020MQTT'
MQTT_CLIENT_ID: 'flights_client'

# MQTT topics
MQTT_TOPIC_CLOSEST_AIRCRAFT: "dev/flights/closest"
MQTT_TOPIC_VISIBLE: "dev/flights/visible"

# Preferred image format
IMAGE_FORMAT: "svg"  # png or svg; If one is not available, the other will be served if available

# HTTP server configuration
FASTAPI_PORT: 47474

# Configuration for flight counts
COUNT_FLIGHTS: true
TIME_PERIODS:
  - today
  - yesterday
  - previous_seven_days
  - previous_thirty_days
  - previous_year

# User location
USE_LAT_LON_FROM_CONFIG: False  # If False, replace by values from receiver dump file
USER_LAT: 51.462649
USER_LON: -0.328869

# Watch zone configuration
LAT_SOUTH: 51.45538
LAT_NORTH: 51.48787
LON_WEST: -0.37257
LON_EAST: -0.28753
MAX_ALT: 3000
MIN_ALT: 0

# Altitude & Distance configuration
RADIUS: 10  # Distance in unit below from user position
DISTANCE_UNIT: mi  # mi for miles or km for kilometers
ALTITUDE_UNIT: ft
ALTITUDE_TRENDS:
  LEVEL_THRESHOLD: 250  # ft/min
  SYMBOLS:
    UP: "⬈"  # or "\u2B08"
    DOWN: "⬊"  # or "\u2B0A"
    LEVEL: "→"  # or "\u2192"

# Source URLs
DUMP_URL: 'http://10.10.30.139:30053/ajax/aircraft'

# File paths relative to project root
CONFIG_FILE_PATH: "config/config.yaml"
REFERENCE_DUMP_FILE_PATH: "config/planefinder_dump_structure.json"

# Output file paths relative to project root
VISIBLE_JSON_FILE_PATH: "output/visible.json"
CLOSEST_AIRCRAFT_JSON_FILE_PATH: "output/closest_aircraft.json"
ALL_AIRCRAFT_JSON_FILE_PATH: "output/all_aircraft.json"
FLIGHTS_WITHIN_DEFINED_ZONE_JSON_FILE_PATH: "output/flights_within_defined_zone.json"
FLIGHTS_WITHIN_DEFINED_RADIUS_JSON_FILE_PATH: "output/flights_within_defined_radius.json"

# Key names for referenced keys in the dump file
tracked_parent: 'aircraft'  # Name of the parent key of tracked flights in the dump, e.g., 'aircraft'
icao_id: 'False'  # Example val: 'AA37CE'
callsign: 'callsign'  # Example val: 'AAL38'
flightno: 'flightno'  # Example val: 'AA38'
route: 'route'  # Example val: 'MIA-LHR'
type: 'type'  # Example val: 'B772'
latitude: 'lat'  # Example val: '51.47807'
longitude: 'lon'  # Example val: '-0.185242'
altitude: 'altitude'  # Example val: '3425'
heading: 'heading'  # Example val: '271'
speed: 'speed'  # Example val: '177'
reg: 'reg'  # Example val: 'N758AN'

# Unused variables
# Tracking
# nearest_aircraft: True
# nearest_aircraft_in_interest_zone: True

# Watch heading
# watch_heading: 270  # Only consider aircraft with this heading; Useful, for example, to watch a take off or landing path
# heading_range: 360  # Degrees plus or minus the watched_heading which still fall into the consideration range

# HA_MQTT_DISCOVERY
HA_MQTT_DISCOVERY: true

# MQTT configuration variables
CONFIG_TOPIC: "homeassistant/device/dev_flights/config"
SW_VERSION: "beta"
DEVICE_IDENTIFIERS_PREFIX: "flights"  
CLOSEST_UNIQUE_ID_PREFIX: "closest"
VISIBLE_UNIQUE_ID_PREFIX: "visible"
CLOSEST_NAME: "Closest Aircraft"
VISIBLE_NAME: "Visible Aircraft"  

# MQTT configuration topic & payload
HA_MQTT_DISCOVERY_CONFIG: >
  {
      "device": {
          "identifiers": ["${DEVICE_IDENTIFIERS}"],
          "name": "Flights",
          "manufacturer": "RS",
          "name": "Flights",
          "sw_version": "${SW_VERSION}",
          "configuration_url": "${CONFIGURATION_URL}"
      },
      "origin": {
          "name": "Flights",
          "sw": "beta",
          "support_url": "https://github.com/ronschaeffer/flights"
      },
      "components": {
          "closest_aircraft": {
              "platform": "sensor",
              "unit_of_measurement": "${DISTANCE_UNIT}",
              "name": "${CLOSEST_NAME}",
              "icon": "mdi:airplane", 
              "state_topic": "${MQTT_TOPIC_CLOSEST_AIRCRAFT}",
              "value_template": "{% set first_key = value_json.keys() | list | first %}{{ value_json.get(first_key, {}).get('distance_value', 0) | float }}",
              "json_attributes_topic": "${MQTT_TOPIC_CLOSEST_AIRCRAFT}",
              "json_attributes_template": "{% set first_key = value_json.keys() | list | first %}{{ value_json.get(first_key, {}) | tojson }}",
              "unique_id": "${CLOSEST_UNIQUE_ID}"
          },
          "visible_aircraft": {
              "platform": "sensor",
              "unit_of_measurement": "planes",
              "value_template": "{{ value_json.get('visible_aircraft', 0) }}",
              "name": "${VISIBLE_NAME}",
              "icon": "mdi:radar",
              "state_topic": "${MQTT_TOPIC_VISIBLE}",
              "json_attributes_topic": "${MQTT_TOPIC_CLOSEST_AIRCRAFT}",
              "json_attributes_template": "{{ value_json | tojson }}",
              "unique_id": "${VISIBLE_UNIQUE_ID}"
          }
      }
  }